sudo: required
dist: trusty
language: c
cache:
  apt: true
  directories:
    - /home/travis/postgresql
env:
  global:
    - enable_coverage=yes
    - PG_PRELOAD=mongodb_fdw
  matrix:
    - PGVERSION=9.6
before_install:
  - git clone -b v0.7.9 --depth 1 https://github.com/citusdata/tools.git
  - sudo make -C tools install
  - setup_apt
  - nuke_pg
install:
  - sudo locale-gen da_DK
  - sudo locale-gen da_DK.utf8
  - sudo rm /etc/apt/sources.list.d/mongodb*.list
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E52529D4
  - sudo bash -c 'echo "deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" > /etc/apt/sources.list.d/mongodb-org-4.0.list'
  - sudo apt update
  - sudo apt install mongodb-org
  - systemctl enable mongod.service
  - systemctl start mongod.service
  - mongo --version
  - sudo apt-get install mongodb mongodb-clients mongodb-server
  - sudo pip install cpp-coveralls
  - sudo apt-get install cmake libssl-dev libsasl2-dev
  - sudo apt-get install libjson-c-dev
  - ./autogen.sh
  - export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig/
  - export LD_LIBRARY_PATH=/usr/local/lib/
  - install_pg
  - make LIB=1 libcompile  
  - sudo chmod 555 /usr/local/lib/* 
  - sudo ldconfig
  - install_custom_pg
before_script:
  - config_and_start_cluster
script: pg_travis_test
after_success:
  - sudo chmod 666 *.gcda
  - coveralls
